/*!
@copyright

    Copyright (c) 2020, MinnowWare. All rights reserved.
    This program and the accompanying materials are licensed and made
    available under the terms and conditions of the BSD License
    which accompanies this distribution.  The full text of the license
    may be found at

    http://opensource.org/licenses/bsd-license.php

    THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
    WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.

@file EfiCallerBaseName.c

@brief C Development Environment (CDE) driver name\n
    
    Supply of the drivers / executables name, for the CDEMOFINE trace infrastructure.
    
    In the EDK build process this file must not be used, since
    'gEfiCallerBaseName' is automatically generated by the build process.


*/
char* gEfiCallerBaseName = CDE_DRIVER_NAME;